version: '3'
services:
  app:
    build: .
    image: appointment_backend:latest
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000