name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: |
          cd docs
          npm install

      - name: Generate JSdoc documentation for frontend
        run: |
          cd docs
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/frontend/website/*/*.jsx > $GITHUB_WORKSPACE/docs/docs/frontend/api.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/frontend/website/*/components/*.jsx > $GITHUB_WORKSPACE/docs/docs/frontend/components_api.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/frontend/website/*/context/*.jsx > $GITHUB_WORKSPACE/docs/docs/frontend/context_api.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/frontend/website/*/pages/*.jsx > $GITHUB_WORKSPACE/docs/docs/frontend/pages_api.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/backend/API/*.js > $GITHUB_WORKSPACE/docs/docs/backend/api.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/backend/DAO/*.js > $GITHUB_WORKSPACE/docs/docs/backend/dao.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/backend/Middlewares/*.js > $GITHUB_WORKSPACE/docs/docs/backend/middlewares.md
          ./node_modules/.bin/jsdoc2md $GITHUB_WORKSPACE/backend/*.js > $GITHUB_WORKSPACE/docs/docs/backend/backend_api.md
      - name: Build website
        run: |
          cd docs
          npm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
