name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Iterate over each directory and run Jest tests
      - name: Run Jest tests
        run: |
          for dir in frontend backend; do
            cd $dir
            npm install
            npm test
            cd ..
          done