name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Jest test on frontend
        run: |
          cd frontend
          cd website
          npm install
          npm test
        
      - name: Run Jest test for backend
        run: |
          cd backend
          npm install
          npm test
